# Generated by Django 3.2.7 on 2022-01-23 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magiclink', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicLinkUnsubscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
