# Generated by Django 4.2.3 on 2023-08-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magiclink", "0002_magiclinkunsubscribe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="magiclink",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="magiclinkunsubscribe",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
